version: '3.7'
services:
  proxy:
    container_name: fn-proxy
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./app.conf:/etc/nginx/conf.d/default.conf
    working_dir: /app
    restart: always
    networks:
      - fn-nw

  app:
    container_name: fn-php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./php.local.ini:/usr/local/etc/php/conf.d/php.local.ini
    working_dir: /app
    environment:
      XDEBUG_CONFIG: idekey=PHPSTORM
      PHP_IDE_CONFIG: serverName=serv
    restart: always
    networks:
      - fn-nw

  database:
    container_name: fn-database
    image: mysql/mysql-server:8.0
    tmpfs:
      - /var/lib/mysql:uid=999,gid=999
    command: mysqld --default-authentication-plugin=mysql_native_password --max_connections=8096 --socket=/tmp/mysql.sock
    ulimits:
      nofile:
        soft: 32768
        hard: 65535
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
    restart: always
    ports:
      - "3306:3306"
    networks:
      - fn-nw

networks:
  fn-nw:
    name: fn-nw
