controllers:
    resource: ../src/Controller/
    type: annotation

controllers-api:
    resource: ../src/Controller/Api
    type: annotation
    prefix: '/api'

kernel:
    resource: ../src/Kernel.php
    type: annotation

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }